name: JUCE Private Push Trigger
on:
  push:
jobs:
  juce-private-push-trigger:
    name: PUSH
    uses: ./.github/workflows/main.yml
    with:
      juce-utils-branch: test
      nightly-targets: ${{ inputs.nightly-targets }}
      triggerer: ${{ inputs.triggerer && inputs.triggerer || github.event.sender.login }}
      cpp-std: ${{ inputs.cpp-std }}
    secrets: inherit

