name: JUCE Private Nightly Trigger
on:
  schedule:
    - cron: '*/5 * * * *'
env:
  GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TRIGGER_WORKFLOW_REF: main
jobs:
  juce-private-nightly-trigger:
    name: JUCE Nightly Trigger
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          sparse-checkout: ./.github/workflows
      - env:
          TRIGGER_WORKFLOW_INPUTS: |
            {"triggerer":"Nightly Build","nightly-targets":["a","b"]}
        run: python3 ./.github/workflows/trigger_workflow.py
      - env:
          TRIGGER_WORKFLOW_INPUTS: |
            {"triggerer":"Nightly Build C++20","cpp-std":"20"}
        run: python3 ./.github/workflows/trigger_workflow.py
      - env:
          TRIGGER_WORKFLOW_INPUTS: |
            {"triggerer":"Nightly Build C++23","cpp-std":"23"}
        run: python3 ./.github/workflows/trigger_workflow.py

